### ISSUE TITLE
In a multi-module mvn project, reference to CP may fail #3

### ISSUE THREAD

**Issue by karrayhamdi** [cmarchand/maven-catalogBuilder-plugin#5]
Hi,

does not work in this [example](https://bitbucket.org/elsgestion/bofip-versionning/commits/dbf68b4fdd6536afa71378f84b5ab4d3877e8d6b) 

Thanks :)

**Comment by cmarchand** [comment]
Not granted on this projet...

**Comment by cmarchand** [comment]
This project doesn't build, due to dependency not present in nexus.lefebvre-sarrut.eu.

    [ERROR] Failed to execute goal on project versionning: Could not resolve dependencies for project
    eu.els.sie.efl.chaine.bofip:versionning:jar:0.0.1: The following artifacts could not be resolved:
    eu.els.sie.utils:parallel:jar:0.0.1, eu.els.sie.utils:command-line:jar:1.0.0,
    com.gauloispipe.xml:processing:jar:0.0.2, eu.els.sie.xslt:log4j-xslt-message-listener:jar:0.0.3: Could 
    not find artifact eu.els.sie.utils:parallel:jar:0.0.1 in Nexus-public
    (http://srvic/nexus/content/groups/public) -> [Help 1]

**Comment by karrayhamdi** [comment]
Sorry, my fault. Shoud be correct now.

**Comment by cmarchand** [comment]
This [commit](https://bitbucket.org/elsgestion/bofip-versionning/commits/b410e4c3add16e42b82c6cc79a85825f798d6274?at=release1.1) solves your problem. You have to declare which catalog to use in io.xspec.maven:xspec-maven-plugin.

**Comment by cmarchand** [comment]
xspec-maven-plugin has no `<catalogFile />` configuration parameter defined. Once corrected, everything works correctly.
