### ISSUE TITLE
the DOCTYPE in the catalog.xml generated impose an internet access

### ISSUE THREAD

**Issue by Marc95** [cmarchand/maven-catalogBuilder-plugin#6]
In the catalog generated there is the DOCTYPE definition.
When the catalog is used by the resolver, the DTD have to be validated in case of entities declared inside.
if there is no internet access the resolver isn't able to load the catalog.

The best is to suppress the DOCTYPE and perhaps to validate the generated file against the DTD in case of generation error.

**Comment by cmarchand** [comment]
Solved in 1.1.0
